version: '2'

services:
  web_data:
    build: ./frontend
    volumes:
      - ./frontend/public:/usr/local/nginx/html:ro

  nginx:
    build: ./nginx
    volumes_from:
      - web_data
    links:
      - restapi
    ports:
      - "80:80"

  restapi:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app:ro
    environment:
      - MODE=dev
    ports:
      - "5000:5000"
  