version: '2'

services:
  web_data:
    build: ./frontend
    volumes:
      - ./frontend/public:/usr/local/nginx/html:ro

  nginx:
    build: ./nginx
    volumes_from:
      - web_data
    links:
      - restapi
    ports:
      - "80:80"

  restapi:
    restart: always
    build: ./sentiment_webservice
    volumes:
      - ./sentiment_webservice:/usr/src/app
    expose:
      - "5000"
    ports:
      - "5000:5000"
  